/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/header/AppHeader.vue')['default']
    Backdrop: typeof import('./components/ui/Backdrop.vue')['default']
    Hamburger: typeof import('./components/header/Hamburger.vue')['default']
    NavList: typeof import('./components/header/NavList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
